version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql.Dockerfile
    image: mysql_db
    restart: unless-stopped
    container_name: mysql_db
    ports:
      - 3307:3306
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql
    env_file:
      - ./envs/mysql.env
    user: "1000:1000"

  db_manager:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    env_file:
      - ./envs/phpmyadmin.env
    ports:
      - 6060:80
    container_name: phpmyadmin
